### ISSUE TITLE
Issue - Port change does not allow reconnect [Spout]

### ISSUE THREAD

**Issue by Khormin** [Raphfrk/ServerPort#22]
In the process of trying to figure out the install, I changed the required port for my own client.

Unfortunately, the second server we used this on cannot auto-connect to my own.  This means that with the spout client (102), it's possible to log into the other server automatically, but not back again.

It causes an issue claiming "invalid handshake" and rejects the connection.

**Comment by Raphfrk** [comment]
The best plan is to just delete the 2 server.txt files and try again.  I think this one may have been solved in the thread?

**Comment by Khormin** [comment]
Unfortunately no.  Not with the combined issue of the servers.txt being untouched.  Deleting servers.txt simply means the two servers don't communicate.

**Comment by Raphfrk** [comment]
I am not sure what is causing that.  Maybe it is a directory permissions thing?

**Comment by Khormin** [comment]
I've checked that over.  It's able to interact with some folders, not with the main plugin folder itself.  I'm not getting the same issue with other jar files being unpacked, either.

Checked my java settings, it isn't putting java code to the sandbox, and my firewall being turned offline doesn't fix the issue.  Ironically, it's able to update the portal to the world directory, as well.

**Comment by Raphfrk** [comment]
That is very strange.  I wonder if deleting the folder and starting again would help.

However, since it is working now, maybe no big deal.

**Comment by Khormin** [comment]
/nod.  Other than the random people booting, that's about it.  Thought you'd
appreciate the heads-up.

On 29/08/2011 7:23 PM, "Raphfrk" <
reply@reply.github.com>
wrote:
